config/routes.rb
Teamworker::Application.routes.draw do
  resources :timeboxes

  resources :teams

  get "report/index"

  resources :supplies

  resources :days

  resources :people

  get "home/index"

  devise_for :users

  root :to => "Home#index"

end

app/models/supply.rb
class Supply < ActiveRecord::Base
  belongs_to :person
  belongs_to :team
  attr_accessible :start_date, :end_date, :person_id
end

app/controllers/supplies_controller.rb
class SuppliesController < ApplicationController
  def index
    @supplies = Supply.all
  end

  def show
    @supply = Supply.find(params[:id])
  end

  def new
    @supply = Supply.new
  end

  def create
    @supply = Supply.new(params[:supply])
    if @supply.save
      redirect_to @supply, :notice => "Successfully created supply."
    else
      render :action => 'new'
    end
  end

  def edit
    @supply = Supply.find(params[:id])
  end

  def update
    @supply = Supply.find(params[:id])
    if @supply.update_attributes(params[:supply])
      redirect_to @supply, :notice  => "Successfully updated supply."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @supply = Supply.find(params[:id])
    @supply.destroy
    redirect_to supplies_url, :notice => "Successfully destroyed supply."
  end
end

app/helpers/supplies_helper.rb
module SuppliesHelper
end

app/views/supplies/_form.html.erb
<%= form_for @supply do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :start_date %><br />
    <%= f.date_select :start_date %>
  </p>
  <p>
    <%= f.label :end_date %><br />
    <%= f.date_select :end_date %>
  </p>
  <p>
    <%= f.label :person_id %><br />
    <%= f.text_field :person_id %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/supplies/edit.html.erb
<% title "Edit Supply" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @supply %> |
  <%= link_to "View All", supplies_path %>
</p>

app/views/supplies/index.html.erb
<% title "Supplies" %>

<table>
  <tr>
    <th>Start Date</th>
    <th>End Date</th>
    <th>Person</th>
  </tr>
  <% for supply in @supplies %>
    <tr>
      <td><%= supply.start_date %></td>
      <td><%= supply.end_date %></td>
      <td><%= supply.person_id %></td>
      <td><%= link_to "Show", supply %></td>
      <td><%= link_to "Edit", edit_supply_path(supply) %></td>
      <td><%= link_to "Destroy", supply, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Supply", new_supply_path %></p>

app/views/supplies/new.html.erb
<% title "New Supply" %>

<%= render 'form' %>

<p><%= link_to "Back to List", supplies_path %></p>

app/views/supplies/show.html.erb
<% title "Supply" %>

<p>
  <strong>Start Date:</strong>
  <%= @supply.start_date %>
</p>
<p>
  <strong>End Date:</strong>
  <%= @supply.end_date %>
</p>
<p>
  <strong>Person:</strong>
  <%= @supply.person_id %>
</p>

<p>
  <%= link_to "Edit", edit_supply_path(@supply) %> |
  <%= link_to "Destroy", @supply, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", supplies_path %>
</p>