config/routes.rb
Teamworker::Application.routes.draw do
  resources :timeboxes

  resources :teams

  get "report/index"

  resources :supplies

  resources :days

  resources :people

  get "home/index"

  devise_for :users

  root :to => "Home#index"

end

app/models/day.rb
class Day < ActiveRecord::Base
  attr_accessible :date, :work_day, :holiday_name
  
end

app/controllers/days_controller.rb
class DaysController < ApplicationController
  def index
    @days = Day.all
  end

  def show
    @day = Day.find(params[:id])
  end

  def new
    @day = Day.new
  end

  def create
    @day = Day.new(params[:day])
    if @day.save
      redirect_to @day, :notice => "Successfully created day."
    else
      render :action => 'new'
    end
  end

  def edit
    @day = Day.find(params[:id])
  end

  def update
    @day = Day.find(params[:id])
    if @day.update_attributes(params[:day])
      redirect_to @day, :notice  => "Successfully updated day."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @day = Day.find(params[:id])
    @day.destroy
    redirect_to days_url, :notice => "Successfully destroyed day."
  end
end

app/helpers/days_helper.rb
module DaysHelper
end

app/views/days/_form.html.erb
<%= form_for @day do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :date %><br />
    <%= f.date_select :date %>
  </p>
  <p>
    <%= f.label :work_day %><br />
    <%= f.check_box :work_day %>
  </p>
  <p>
    <%= f.label :holiday_name %><br />
    <%= f.text_field :holiday_name %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/days/edit.html.erb
<% title "Edit Day" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @day %> |
  <%= link_to "View All", days_path %>
</p>

app/views/days/index.html.erb
<% title "Days" %>

<table>
  <tr>
    <th>Date</th>
    <th>Work Day</th>
    <th>Holiday Name</th>
  </tr>
  <% for day in @days %>
    <tr>
      <td><%= day.date %></td>
      <td><%= day.work_day %></td>
      <td><%= day.holiday_name %></td>
      <td><%= link_to "Show", day %></td>
      <td><%= link_to "Edit", edit_day_path(day) %></td>
      <td><%= link_to "Destroy", day, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Day", new_day_path %></p>

app/views/days/new.html.erb
<% title "New Day" %>

<%= render 'form' %>

<p><%= link_to "Back to List", days_path %></p>

app/views/days/show.html.erb
<% title "Day" %>

<p>
  <strong>Date:</strong>
  <%= @day.date %>
</p>
<p>
  <strong>Work Day:</strong>
  <%= @day.work_day %>
</p>
<p>
  <strong>Holiday Name:</strong>
  <%= @day.holiday_name %>
</p>

<p>
  <%= link_to "Edit", edit_day_path(@day) %> |
  <%= link_to "Destroy", @day, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", days_path %>
</p>