config/routes.rb
Teamworker::Application.routes.draw do
  resources :timeboxes

  resources :teams

  get "report/index"

  resources :supplies

  resources :days

  resources :people

  get "home/index"

  devise_for :users

  root :to => "Home#index"

end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "TeamWorker" %></title>
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag :defaults %>
    <script type="text/javascript" src="http://www.google.com/jsapi"></script>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body>
    <div id="container">
      <div id="logo">Team Worker</div><div id="toolbar"><% if user_signed_in? %><%= image_tag current_user.gravatar_url(:size => "30") %><div id="login"><%= "Logged in as #{current_user.email}" %> <%= link_to("Log out", :destroy_user_session) %></div><% end %></div>
      <div class="clear"></div>
      <div id="access"><div class="menu-header"><ul class="menuheader">
        <li><%= link_to "People", people_path %></li>
        <li><%= link_to "Days", days_path %></li>
        <li><%= link_to "Supplies", supplies_path %></li>
        <li><%= link_to "Reports", report_index_path %></li>
      </ul></div></div>
      <div class="clear"></div>
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <%= content_tag :h1, yield(:title) if show_title? %>
      <%= yield %>
    </div>
  </body>
</html>